{
 "title": "Spark Jobs",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", namespace=~\"^.*-(ha|kyuubi)$\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Running Spark Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (job_base) (label_replace(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\".*-exec-.*\",phase=\"Running\"},\"job_base\",\"$1\",\"pod\",\"^(.*)-[^-]+-exec-[^-]+$\")))"
    }
   ]
  },
  {
   "title": "Running Jobs by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count by (namespace) (count by (namespace, job_base) (label_replace(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\".*-exec-.*\",phase=\"Running\"},\"job_base\",\"$1\",\"pod\",\"^(.*)-[^-]+-exec-[^-]+$\")))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Executor Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count by (namespace) (\r\n  kube_pod_status_phase{\r\n    namespace=~\"$namespace\",\r\n    pod=~\".*-exec-.*\",\r\n    phase=\"Running\"\r\n  }\r\n)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "count (\r\n  kube_pod_status_phase{\r\n    namespace=~\"$namespace\",\r\n    pod=~\".*-exec-.*\",\r\n    phase=\"Running\"\r\n  }\r\n)",
     "legendFormat": "Total-Executor-Count"
    }
   ]
  },
  {
   "title": "Executor Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count by (namespace) (label_replace(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\".*-exec-.*\",phase=\"Running\"},\"job_base\",\"$1\",\"pod\",\"^(.*)-[^-]+-exec-[^-]+$\"))",
     "legendFormat": "Total-Executor-Count"
    },
    {
     "expr": "count by (namespace, job_base) (label_replace(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\".*-exec-.*\",phase=\"Running\"},\"job_base\",\"$1\",\"pod\",\"^(.*)-[^-]+-exec-[^-]+$\"))",
     "legendFormat": "{{namespace}} / {{job_base}}"
    }
   ]
  },
  {
   "title": "Executor Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count by (pod_base) (\r\n  label_replace(\r\n    kube_pod_status_phase{\r\n      namespace=~\"$namespace\",\r\n      pod=~\".*-exec-.*\",\r\n      phase=\"Running\"\r\n    },\r\n    \"pod_base\",\r\n    \"$1\",\r\n    \"pod\",\r\n    \"(.*)-[a-f0-9]+-exec-.*\"\r\n  )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Executor Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=~\"$namespace\",pod=~\".*-exec-.*\",phase=\"Running\"}"
    }
   ]
  }
 ]
}