SELECT SS.SESS_NO
     , SS.SCEN_NAME
     , SS.SCEN_VERSION
     , SS.SESS_NAME
     , SS.PARENT_SESS_NO
     , SS.SESS_BEG
     , SS.SESS_END
     , SS.SESS_STATUS
     , DECODE(SS.SESS_STATUS, 'D', 'Done', 'E', 'Error', 'M', 'Warning', 'Q', 'Queued', 'R', 'Running', 'W', 'Waiting', SS.SESS_STATUS) AS SESS_STATUS_DESC
     , SSL.NNO
     , SSTL.NB_RUN
     , SST.TASK_TYPE
     , DECODE(SST.TASK_TYPE, 'C', 'Loading', 'J', 'Mapping', 'S', 'Procedure', 'V', 'Variable', SST.TASK_TYPE) AS TASK_TYPE_DESC
     , SST.EXE_CHANNEL
     , DECODE(SST.EXE_CHANNEL, 'B', 'Oracle Data Integrator Scripting', 'C', 'Oracle Data Integrator Connector', 'J', 'JDBC', 'O', 'Operating System', 'Q', 'Queue', 'S', 'Oracle Data Integrator Command', 'T', 'Topic', 'U', 'XML Topic', SST.EXE_CHANNEL) AS EXE_CHANNEL_DESC
     , SSTL.SCEN_TASK_NO
     , SST.PAR_SCEN_TASK_NO
     , SST.TASK_NAME1
     , SST.TASK_NAME2
     , SST.TASK_NAME3
     , SSTL.TASK_DUR
     , SSTL.NB_ROW
     , SSTL.NB_INS
     , SSTL.NB_UPD
     , SSTL.NB_DEL
     , SSTL.NB_ERR
     , SSS.LSCHEMA_NAME || '.' || SSS.RES_NAME AS TARGET_TABLE
     , CASE WHEN SST.COL_TECH_INT_NAME IS NOT NULL AND SST.COL_LSCHEMA_NAME IS NOT NULL THEN SST.COL_TECH_INT_NAME || '.' || SST.COL_LSCHEMA_NAME
            ELSE NULL
       END AS TARGET_SCHEMA
     , SSTL.DEF_TXT AS TARGET_COMMAND
     , CASE WHEN SST.DEF_TECH_INT_NAME IS NOT NULL AND SST.DEF_LSCHEMA_NAME IS NOT NULL THEN SST.DEF_TECH_INT_NAME || '.' || SST.DEF_LSCHEMA_NAME
            ELSE NULL
       END AS SOURCE_SCHEMA
     , SSTL.COL_TXT AS SOURCE_COMMAND
  FROM SNP_SESSION SS
    INNER JOIN SNP_STEP_LOG SSL
        ON SS.SESS_NO = SSL.SESS_NO
    INNER JOIN SNP_SESS_TASK_LOG SSTL
        ON SS.SESS_NO = SSTL.SESS_NO
    INNER JOIN SNP_SB_TASK SST
        ON SSTL.SB_NO = SST.SB_NO
        AND SSTL.SCEN_TASK_NO = SST.SCEN_TASK_NO
        AND SSL.NNO = SSTL.NNO
        AND SSTL.NNO = SST.NNO
        AND SSL.NB_RUN = SSTL.NB_RUN
    LEFT JOIN SNP_SB_STEP SSS
        ON SST.SB_NO = SSS.SB_NO
        AND SST.NNO = SSS.NNO
WHERE 1 = 1
   AND SS.SESS_BEG > TO_DATE('20241005','yyyymmdd')
   -- AND SS.SESS_NO = 123542
   AND SST.EXE_CHANNEL IN ('B', 'C', 'J', 'S')
   AND (UPPER(SSTL.DEF_TXT) LIKE '%SELECT%' OR UPPER(SSTL.DEF_TXT) LIKE '%MERGE%' OR UPPER(SSTL.DEF_TXT) LIKE '%INSERT%')
   AND SST.TASK_TYPE NOT IN ('V') --VARIABLE
   
   -- AND SS.SESS_STATUS IN ('D', 'R', 'M', 'E')   
    and (SS.SESS_STATUS = 'E'
        OR (SS.SESS_STATUS = 'M' AND SSTL.NB_ERR > 0) -- IN ('D', 'R', 'M', 'E')   
    )
   
--ORDER BY SS.SESS_NO DESC, SSL.NNO, SSL.NB_RUN, SSTL.SCEN_TASK_NO;
ORDER BY SS.SCEN_NAME ASC, SS.SESS_BEG ASC, SSL.NNO, SSL.NB_RUN, SSTL.SCEN_TASK_NO;