drop table ETL_CONFIG.ADVANCED_HISTOGRAMS_COLLECTED;

CREATE TABLE ETL_CONFIG.ADVANCED_HISTOGRAMS_COLLECTED AS
SELECT
    DATABASE_NAME,
    TABLE_NAME,
    'ANALYZE TABLE ' || DATABASE_NAME || '.' || TABLE_NAME || ' COLUMNS ' || GROUP_CONCAT(DISTINCT COLUMN_NAME) || ' ENABLE;' statement
FROM
    information_schema.ADVANCED_HISTOGRAMS
WHERE
    1 = 1
    AND DATABASE_NAME in ('SAY_DWH')
GROUP BY
    DATABASE_NAME,
    TABLE_NAME;

CREATE TABLE `MAINTENANCE_LOGS` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT,
    `LOG_DESC` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
    `STATEMENT` longtext CHARACTER SET utf8 COLLATE utf8_general_ci,
    `LOG_TS` datetime(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`ID`),
    SHARD KEY `__SHARDKEY` (`ID`),
    SORT KEY `__UNORDERED` ()
) AUTO_INCREMENT = 2736 AUTOSTATS_CARDINALITY_MODE = INCREMENTAL AUTOSTATS_HISTOGRAM_MODE = CREATE AUTOSTATS_SAMPLING = ON SQL_MODE = 'PIPES_AS_CONCAT,ANSI_QUOTES,ONLY_FULL_GROUP_BY,STRICT_ALL_TABLES';

CREATE PROCEDURE `ETL_CONFIG`.`MAINTAIN_TABLES`() RETURNS void DEFINER = 'root' @'%' AS declare - - fixed stats generated by report usage ctables query(
    DATABASE_NAME varchar(200),
    TABLE_NAME varchar(200),
    statement longtext
) =
select
    DATABASE_NAME,
    TABLE_NAME,
    STATEMENT
from
    ETL_CONFIG.ADVANCED_HISTOGRAMS_COLLECTED
order by
    DATABASE_NAME,
    TABLE_NAME;

- - recomended stats ctables_recomended query(
    DATABASE_NAME varchar(200),
    TABLE_NAME varchar(200),
    statement longtext
) =
SELECT
    DATABASE_NAME,
    TABLE_NAME,
    'ANALYZE TABLE ' || database_name || '.' || table_name || ' columns ' || group_concat(distinct column_name) || ' enable;' statement
from
    information_schema.mv_query_prospective_histograms
where
    database_name <> 'information_schema'
group by
    database_name,
    table_name
order by
    database_name,
    table_name;

statement_optimize text;

begin for tlist in collect(ctables) loop execute immediate tlist.statement;

execute immediate 'INSERT INTO ETL_CONFIG.MAINTENANCE_LOGS (LOG_DESC,STATEMENT) values (''HISTOGRAM COLLECTION_FIX'',''' || tlist.statement || ''')';

statement_optimize = 'OPTIMIZE TABLE ' || tlist.DATABASE_NAME || '.' || tlist.TABLE_NAME;

execute immediate statement_optimize;

execute immediate 'INSERT INTO ETL_CONFIG.MAINTENANCE_LOGS (LOG_DESC,STATEMENT) values (''OPTIMIZE TABLE_FIX'',''' || statement_optimize || ''')';

end loop;

for tlist in collect(ctables_recomended) loop execute immediate tlist.statement;

execute immediate 'insert into ETL_CONFIG.MAINTENANCE_LOGS (LOG_DESC,STATEMENT) values (''HISTOGRAM COLLECTION_RECOMENDED'',''' || tlist.statement || ''')';

statement_optimize = 'OPTIMIZE TABLE ' || tlist.DATABASE_NAME || '.' || tlist.TABLE_NAME;

execute immediate statement_optimize;

execute immediate 'INSERT INTO ETL_CONFIG.MAINTENANCE_LOGS (LOG_DESC,STATEMENT) values (''OPTIMIZE TABLE'',''' || statement_optimize || ''')';

end loop;

end;