-- stg.vw_bhs_bsm_flight_inc source
-- Converted from Greenplum to Spark SQL

CREATE OR REPLACE VIEW stg.vw_bhs_bsm_flight_inc
AS SELECT
        CASE
            WHEN q.outbound_flight_date IS NOT NULL THEN concat(concat_ws('|', date_format(CAST(q.outbound_flight_date AS TIMESTAMP), 'yyyyMMdd'), q.oub_flight_number), '|', COALESCE(q.`[.P/] Passenger Name`, ''))
            ELSE NULL
        END AS bhs_passenger_dep_uniq,
        CASE
            WHEN q.inbound_flight_date IS NOT NULL THEN concat(concat_ws('|', date_format(CAST(q.inbound_flight_date AS TIMESTAMP), 'yyyyMMdd'), q.inb_flight_number), '|', COALESCE(q.`[.P/] Passenger Name`, ''))
            ELSE NULL
        END AS bhs_passenger_arr_uniq,
    concat(concat_ws('|', date_format(CAST(q.inbound_flight_date AS TIMESTAMP), 'yyyyMMdd'), q.inb_flight_number, date_format(CAST(q.outbound_flight_date AS TIMESTAMP), 'yyyyMMdd'), q.oub_flight_number), '|', COALESCE(q.`[.P/] Passenger Name`, '')) AS bhs_passenger_uniq_x,
    q.od_median_duration_interval,
    q.estimated_departure_fromorg,
    q.estimated_arrival,
    q.is_nextday,
    CURRENT_TIMESTAMP AS upsert_time_final,
    from_utc_timestamp(q.eventts + interval 3 hours, 'Europe/Istanbul') AS eventts_ist,
    q.inbound_flight_date_time_final,
    q.outbound_flight_date_time_final,
    q.inbound_gate_final,
    q.outbound_gate_final,
    q.hash,
    q.bhs_pk,
    q.message,
    q.message_type,
    q.bsm_chg_del,
    q.`[.V/] Version and Supplementary Data`,
    q.`[.K/] Default Message Printer`,
    q.`[.J/] Processing Information`,
    q.`[.I/] Inbound Flight Information`,
    q.`[.F/] Outbound Flight Information`,
    q.`[.O/] Onward Flight Information`,
    q.inbound_flight_number,
    q.inbound_flight_date_txt,
    q.inbound_flight_date,
    q.inbound_departure_airport,
    q.inbound_booking_class,
    q.outbound_flight_number,
    q.outbound_flight_date_txt,
    q.outbound_flight_date,
    q.outbound_departure_airport,
    q.outbound_booking_class,
    q.onward_flight_number,
    q.onward_flight_date_txt,
    q.onward_flight_date,
    q.onward_departure_airport,
    q.onward_booking_class,
    q.`[.U/] Loading Data`,
    q.`[.N/] Baggage Tag Details`,
    q.`[.B/] Baggage Irregularities`,
    q.`[.Q/] Load Sequence Number`,
    q.`[.S/] Reconciliation Data`,
    q.`[.P/] Passenger Name`,
    q.`[.Y/] Frequent Traveller Number`,
    q.`[.C/] Corporate Or Group Name`,
    q.`[.L/] Automated PNR Address`,
    q.`[.E/] Baggage Exception Data`,
    q.`[.R/] Internal Airline Data`,
    q.`[.X/] Baggage Security Screening`,
    q.`[.T/] Baggage Tag Printer ID`,
    q.`[.A/] Baggage Routing Information `,
    q.`[.D/] Departure Airport / Date Info`,
    q.`[.M/] Manual Tag Indicator`,
    q.`[.H/] Handling Information`,
    q.`[.W/] Pieces And Weight Data`,
    q.weight_first_c,
    q.weight_pieces,
    q.`weight(kg)`,
    q.idevent,
    q.key,
    q.eventts,
    q.insertts,
    q.eventtime,
    q.upsert_time,
    q.passive,
    q.gpid,
    q.outbound_flight_number_orj,
    q.oub_airline_iata,
    q.oub_remaining_part,
    q.oub_flight_number,
    q.inbound_flight_number_orj,
    q.inb_airline_iata,
    q.inb_remaining_part,
    q.inb_flight_number,
    q.inb_flight_nature,
    q.inb_international_status,
    q.out_flight_nature,
    q.out_international_status,
    q.inb_sto_flight_nature,
    q.inb_sto_international_status,
    q.outb_sto_flight_nature,
    q.outb_sto_international_status,
    q.inb_flight_nature_final,
    q.out_flight_nature_final,
    q.inb_international_status_final,
    q.out_international_status_final,
        CASE
            WHEN q.inb_flight_nature_final_raw = 'ARRIVAL' AND q.out_flight_nature_final_raw IS NULL AND q.inbound_flight_date_time_final IS NOT NULL THEN concat('O&D ARRIVAL [',
            CASE
                WHEN q.inb_international_status_final_raw = 'DOMESTIC' THEN 'dom'
                WHEN q.inb_international_status_final_raw = 'INTERNATIONAL' THEN 'int'
                ELSE NULL
            END, ']')
            WHEN q.out_flight_nature_final_raw = 'DEPARTURE' AND q.inb_flight_nature_final_raw IS NULL AND q.outbound_flight_date_time_final IS NOT NULL THEN concat('O&D DEPARTURE [',
            CASE
                WHEN q.out_international_status_final_raw = 'DOMESTIC' THEN 'dom'
                WHEN q.out_international_status_final_raw = 'INTERNATIONAL' THEN 'int'
                ELSE NULL
            END, ']')
            WHEN q.inb_flight_nature_final_raw = 'ARRIVAL' AND q.out_flight_nature_final_raw = 'DEPARTURE' AND q.inbound_flight_date_time_final IS NOT NULL AND q.outbound_flight_date_time_final IS NOT NULL THEN concat('TRANSFER [',
            CASE
                WHEN q.inb_international_status_final_raw = 'DOMESTIC' AND q.out_international_status_final_raw = 'DOMESTIC' THEN 'dom2dom'
                WHEN q.inb_international_status_final_raw = 'DOMESTIC' AND q.out_international_status_final_raw = 'INTERNATIONAL' THEN 'dom2int'
                WHEN q.inb_international_status_final_raw = 'INTERNATIONAL' AND q.out_international_status_final_raw = 'DOMESTIC' THEN 'int2dom'
                WHEN q.inb_international_status_final_raw = 'INTERNATIONAL' AND q.out_international_status_final_raw = 'INTERNATIONAL' THEN 'int2int'
                ELSE NULL
            END, ']')
            WHEN q.inb_flight_nature_final_raw = 'ARRIVAL' AND q.out_flight_nature_final_raw IS NULL AND q.inbound_flight_date_time_final IS NULL THEN concat('O&D ARRIVAL [',
            CASE
                WHEN q.inb_international_status_final_raw = 'DOMESTIC' THEN 'dom'
                WHEN q.inb_international_status_final_raw = 'INTERNATIONAL' THEN 'int'
                ELSE NULL
            END, ']  -  NoFlight')
            WHEN q.out_flight_nature_final_raw = 'DEPARTURE' AND q.inb_flight_nature_final_raw IS NULL AND q.outbound_flight_date_time_final IS NULL THEN concat('O&D DEPARTURE [',
            CASE
                WHEN q.out_international_status_final_raw = 'DOMESTIC' THEN 'dom'
                WHEN q.out_international_status_final_raw = 'INTERNATIONAL' THEN 'int'
                ELSE NULL
            END, ']  -  NoFlight')
            WHEN q.inb_flight_nature_final_raw = 'ARRIVAL' AND q.out_flight_nature_final_raw = 'DEPARTURE' AND q.inbound_flight_date_time_final IS NULL AND q.outbound_flight_date_time_final IS NULL THEN concat('TRANSFER [',
            CASE
                WHEN q.inb_international_status_final_raw = 'DOMESTIC' AND q.out_international_status_final_raw = 'DOMESTIC' THEN 'dom2dom'
                WHEN q.inb_international_status_final_raw = 'DOMESTIC' AND q.out_international_status_final_raw = 'INTERNATIONAL' THEN 'dom2int'
                WHEN q.inb_international_status_final_raw = 'INTERNATIONAL' AND q.out_international_status_final_raw = 'DOMESTIC' THEN 'int2dom'
                WHEN q.inb_international_status_final_raw = 'INTERNATIONAL' AND q.out_international_status_final_raw = 'INTERNATIONAL' THEN 'int2int'
                ELSE NULL
            END, ']  -  NoFlight - inOut')
            WHEN q.inb_flight_nature_final_raw = 'ARRIVAL' AND q.out_flight_nature_final_raw = 'DEPARTURE' AND q.inbound_flight_date_time_final IS NOT NULL AND q.outbound_flight_date_time_final IS NULL THEN concat('TRANSFER [',
            CASE
                WHEN q.inb_international_status_final_raw = 'DOMESTIC' AND q.out_international_status_final_raw = 'DOMESTIC' THEN 'dom2dom'
                WHEN q.inb_international_status_final_raw = 'DOMESTIC' AND q.out_international_status_final_raw = 'INTERNATIONAL' THEN 'dom2int'
                WHEN q.inb_international_status_final_raw = 'INTERNATIONAL' AND q.out_international_status_final_raw = 'DOMESTIC' THEN 'int2dom'
                WHEN q.inb_international_status_final_raw = 'INTERNATIONAL' AND q.out_international_status_final_raw = 'INTERNATIONAL' THEN 'int2int'
                ELSE NULL
            END, ']  -  NoFlight - out')
            WHEN q.inb_flight_nature_final_raw = 'ARRIVAL' AND q.out_flight_nature_final_raw = 'DEPARTURE' AND q.inbound_flight_date_time_final IS NULL AND q.outbound_flight_date_time_final IS NOT NULL THEN concat('TRANSFER [',
            CASE
                WHEN q.inb_international_status_final_raw = 'DOMESTIC' AND q.out_international_status_final_raw = 'DOMESTIC' THEN 'dom2dom'
                WHEN q.inb_international_status_final_raw = 'DOMESTIC' AND q.out_international_status_final_raw = 'INTERNATIONAL' THEN 'dom2int'
                WHEN q.inb_international_status_final_raw = 'INTERNATIONAL' AND q.out_international_status_final_raw = 'DOMESTIC' THEN 'int2dom'
                WHEN q.inb_international_status_final_raw = 'INTERNATIONAL' AND q.out_international_status_final_raw = 'INTERNATIONAL' THEN 'int2int'
                ELSE NULL
            END, ']  -  NoFlight - in')
            ELSE 'E(no_flight_match)'
        END AS `transfer_O&D`,
    q.inbound_flight_date_time,
    q.outbound_flight_date_time,
    q.inbound_flight_date_time_sto,
    q.outbound_flight_date_time_sto,
    q.inb_aircraft_iata,
    q.inb_aircraft_icao,
    q.inb_registration,
    q.inb_pax,
    q.inb_max_pax,
    q.inb_pax_out,
    q.inb_booked_pax,
    q.inb_baggage_in,
    q.inb_baggage_out,
    q.inb_baggage_trans,
    q.inb_cargo_in,
    q.inb_cargo_out,
    q.inb_cargo_trans,
    q.outb_aircraft_iata,
    q.outb_aircraft_icao,
    q.outb_registration,
    q.outb_pax,
    q.outb_max_pax,
    q.outb_pax_out,
    q.outb_booked_pax,
    q.outb_baggage_in,
    q.outb_baggage_out,
    q.outb_baggage_trans,
    q.outb_cargo_in,
    q.outb_cargo_out,
    q.outb_cargo_trans,
    q.inbound_gate,
    q.outbound_gate,
    q.inbound_gate_sto,
    q.outbound_gate_sto,
    q.inb_ams_groundservices,
    q.inb_ams_p_pax,
    q.inb_ams_body_type,
    q.outb_ams_groundservices,
    q.outb_ams_p_pax,
    q.outb_ams_body_type,
    q.ecac,
    q.outbound_departure_country_tr,
    q.outbound_departure_city_tr,
    q.outbound_departure_city,
    q.outbound_departure_country,
    q.outbound_departure_country_latitude,
    q.outbound_departure_country_longitude,
    q.outbound_departure_airport_name,
    q.inbound_country_tr,
    q.inbound_city_tr,
    q.inbound_city,
    q.inbound_country,
    q.inbound_country_latitude,
    q.inbound_country_longitude,
    q.inbound_departure_airport_name,
    q.inbound_ticari_yolcu_sayisi,
    q.outbound_ticari_yolcu_sayisi,
    q.bhs_passenger_uniq,
    q.bhs_passenger_family_4dep,
    q.bhs_passenger_together_reservation_id,
    q.bhs_passenger_together_baggage_id,
    q.bhs_baggage_uniq,
    q.outbound_gate_grup,
    q.inbound_gate_grup,
    q.inbound_outbound_gate_grup,
    q.inbound_outbound_airport_route,
    q.inbound_outbound_country_city_route,
    q.ecac_passenger_uniq,
    q.version1,
    q.version2,
    q.version3,
        CASE
            WHEN q.inbound_flight_date_time_final IS NOT NULL AND q.outbound_flight_date_time_final IS NOT NULL THEN (unix_timestamp(q.outbound_flight_date_time_final) - unix_timestamp(q.inbound_flight_date_time_final)) / 60.0
            ELSE NULL
        END AS wating_time_minutes,
        CASE
            WHEN q.inbound_country IS NOT NULL AND q.outbound_departure_country IS NOT NULL AND (q.outbound_departure_city <> 'ISTANBUL' OR q.inbound_city <> 'ISTANBUL') AND q.inbound_country = 'TURKEY' AND q.outbound_departure_country <> 'TURKEY' AND q.inbound_flight_date_time_final IS NOT NULL AND q.outbound_flight_date_time_final IS NOT NULL THEN 'TRANSFER [dom2int]'
            WHEN q.inbound_country IS NOT NULL AND q.outbound_departure_country IS NOT NULL AND (q.outbound_departure_city <> 'ISTANBUL' OR q.inbound_city <> 'ISTANBUL') AND q.inbound_country <> 'TURKEY' AND q.outbound_departure_country = 'TURKEY' AND q.inbound_flight_date_time_final IS NOT NULL AND q.outbound_flight_date_time_final IS NOT NULL THEN 'TRANSFER [int2dom]'
            WHEN q.inbound_country IS NOT NULL AND q.outbound_departure_country IS NOT NULL AND (q.outbound_departure_city <> 'ISTANBUL' OR q.inbound_city <> 'ISTANBUL') AND q.inbound_country <> 'TURKEY' AND q.outbound_departure_country <> 'TURKEY' AND q.inbound_flight_date_time_final IS NOT NULL AND q.outbound_flight_date_time_final IS NOT NULL THEN 'TRANSFER [int2int]'
            WHEN q.inbound_country IS NOT NULL AND q.outbound_departure_country IS NOT NULL AND (q.outbound_departure_city <> 'ISTANBUL' OR q.inbound_city <> 'ISTANBUL') AND q.inbound_country = 'TURKEY' AND q.outbound_departure_country = 'TURKEY' AND q.inbound_flight_date_time_final IS NOT NULL AND q.outbound_flight_date_time_final IS NOT NULL THEN 'TRANSFER [dom2dom]'
            WHEN q.inbound_country IS NOT NULL AND q.outbound_departure_country IS NULL AND (q.outbound_departure_city <> 'ISTANBUL' OR q.inbound_city <> 'ISTANBUL') AND q.inbound_country = 'TURKEY' AND q.inbound_flight_date_time_final IS NOT NULL THEN 'ARRIVAL [dom]'
            WHEN q.inbound_country IS NOT NULL AND q.outbound_departure_country IS NULL AND (q.outbound_departure_city <> 'ISTANBUL' OR q.inbound_city <> 'ISTANBUL') AND q.inbound_country <> 'TURKEY' AND q.inbound_flight_date_time_final IS NOT NULL THEN 'ARRIVAL [int]'
            WHEN q.inbound_country IS NULL AND q.outbound_departure_country IS NOT NULL AND (q.outbound_departure_city <> 'ISTANBUL' OR q.inbound_city <> 'ISTANBUL') AND q.outbound_departure_country = 'TURKEY' AND q.outbound_flight_date_time_final IS NOT NULL THEN 'DEPARTURE [dom]'
            WHEN q.inbound_country IS NULL AND q.outbound_departure_country IS NOT NULL AND (q.outbound_departure_city <> 'ISTANBUL' OR q.inbound_city <> 'ISTANBUL') AND q.outbound_departure_country <> 'TURKEY' AND q.outbound_flight_date_time_final IS NOT NULL THEN 'DEPARTURE [int]'
            WHEN q.outbound_departure_city = 'ISTANBUL' OR q.inbound_city = 'ISTANBUL' THEN 'OTHERS - IST'
            ELSE 'OTHERS'
        END AS `transfer_O&D_old`,
        CASE
            WHEN q.inbound_flight_number IS NOT NULL AND q.outbound_flight_number IS NOT NULL THEN concat(COALESCE(q.inbound_country, ''), '[', initcap(COALESCE(q.inbound_city, '')), '] - [Ist] - ', COALESCE(q.outbound_departure_country, ''), '[', initcap(COALESCE(q.outbound_departure_city, '')), ']')
            WHEN q.inbound_flight_number IS NOT NULL AND q.outbound_flight_number IS NULL THEN concat(COALESCE(q.inbound_country, ''), '[', initcap(COALESCE(q.inbound_city, '')), '] - [Ist]')
            WHEN q.inbound_flight_number IS NULL AND q.outbound_flight_number IS NOT NULL THEN concat('[Ist] - ', COALESCE(q.outbound_departure_country, ''), '[', initcap(COALESCE(q.outbound_departure_city, '')), ']')
            ELSE NULL
        END AS rota_bhs_transfer_city,
        CASE
            WHEN q.inbound_flight_number IS NOT NULL AND q.outbound_flight_number IS NOT NULL THEN concat(COALESCE(q.inbound_country, ''), '[', initcap(COALESCE(q.inbound_departure_airport_name, '')), '] - [Ist] - ', COALESCE(q.outbound_departure_country, ''), '[', initcap(COALESCE(q.outbound_departure_airport_name, '')), ']')
            WHEN q.inbound_flight_number IS NOT NULL AND q.outbound_flight_number IS NULL THEN concat(COALESCE(q.inbound_country, ''), '[', initcap(COALESCE(q.inbound_departure_airport_name, '')), '] - [Ist]')
            WHEN q.inbound_flight_number IS NULL AND q.outbound_flight_number IS NOT NULL THEN concat('[Ist] - ', COALESCE(q.outbound_departure_country, ''), '[', initcap(COALESCE(q.outbound_departure_airport_name, '')), ']')
            ELSE NULL
        END AS rota_bhs_transfer_airport,
        CASE
            WHEN q.inbound_flight_number IS NOT NULL AND q.outbound_flight_number IS NOT NULL THEN concat('in[', COALESCE(q.inbound_flight_number, ''), ' ', q.inbound_flight_date, '] - out[', COALESCE(q.outbound_flight_number, ''), ' ', q.outbound_flight_date, ']')
            WHEN q.inbound_flight_number IS NOT NULL AND q.outbound_flight_number IS NULL THEN concat('in[', COALESCE(q.inbound_flight_number, ''), ' ', q.inbound_flight_date, ']')
            WHEN q.inbound_flight_number IS NULL AND q.outbound_flight_number IS NOT NULL THEN concat('out[', COALESCE(q.outbound_flight_number, ''), ' ', q.outbound_flight_date, ']')
            ELSE NULL
        END AS rota_bhs,
        CASE
            WHEN q.inbound_flight_date_time_final IS NOT NULL AND q.outbound_flight_date_time_final IS NOT NULL THEN concat('ts(', CAST(from_utc_timestamp(q.eventts + interval 3 hours, 'Europe/Istanbul') AS STRING), ') in[', COALESCE(q.inbound_flight_number, ''), ' ', CAST(q.inbound_flight_date_time_final AS STRING), ' g(', COALESCE(q.inbound_gate_final, ''), ') ] - out[', COALESCE(q.outbound_flight_number, ''), ' ', CAST(q.outbound_flight_date_time_final AS STRING), ' g(', COALESCE(q.outbound_gate_final, ''), ') ]')
            WHEN q.inbound_flight_date_time_final IS NOT NULL AND q.outbound_flight_date_time_final IS NULL THEN concat('ts(', CAST(from_utc_timestamp(q.eventts + interval 3 hours, 'Europe/Istanbul') AS STRING), ') in[', COALESCE(q.inbound_flight_number, ''), ' ', CAST(q.inbound_flight_date_time_final AS STRING), ' g(', COALESCE(q.inbound_gate_final, ''), ') ]')
            WHEN q.inbound_flight_date_time_final IS NULL AND q.outbound_flight_date_time_final IS NOT NULL THEN concat('ts(', CAST(from_utc_timestamp(q.eventts + interval 3 hours, 'Europe/Istanbul') AS STRING), ') out[', COALESCE(q.outbound_flight_number, ''), ' ', CAST(q.outbound_flight_date_time_final AS STRING), ' g(', COALESCE(q.outbound_gate_final, ''), ') ]')
            ELSE NULL
        END AS rota_flight
   FROM ( SELECT
                CASE
                    WHEN q1.inb_flight_nature IS NOT NULL THEN q1.inb_flight_nature
                    ELSE q1.inb_sto_flight_nature
                END AS inb_flight_nature_final,
                CASE
                    WHEN q1.out_flight_nature IS NOT NULL THEN q1.out_flight_nature
                    ELSE q1.outb_sto_flight_nature
                END AS out_flight_nature_final,
                CASE
                    WHEN q1.inb_international_status IS NOT NULL THEN q1.inb_international_status
                    ELSE q1.inb_sto_international_status
                END AS inb_international_status_final,
                CASE
                    WHEN q1.out_international_status IS NOT NULL THEN q1.out_international_status
                    ELSE q1.outb_sto_international_status
                END AS out_international_status_final,
                CASE
                    WHEN q1.inbound_flight_date IS NOT NULL THEN 'ARRIVAL'
                    ELSE NULL
                END AS inb_flight_nature_final_raw,
                CASE
                    WHEN q1.outbound_flight_date IS NOT NULL THEN 'DEPARTURE'
                    ELSE NULL
                END AS out_flight_nature_final_raw,
                CASE
                    WHEN q1.inbound_country = 'TURKEY' THEN 'DOMESTIC'
                    ELSE 'INTERNATIONAL'
                END AS inb_international_status_final_raw,
                CASE
                    WHEN q1.outbound_departure_country = 'TURKEY' THEN 'DOMESTIC'
                    ELSE 'INTERNATIONAL'
                END AS out_international_status_final_raw,
                CASE
                    WHEN q1.inbound_flight_date_time IS NOT NULL AND q1.inbound_flight_date_time_sto IS NULL THEN CAST(q1.inbound_flight_date_time AS TIMESTAMP)
                    WHEN q1.inbound_flight_date_time IS NULL AND q1.inbound_flight_date_time_sto IS NOT NULL THEN q1.inbound_flight_date_time_sto
                    ELSE CAST(q1.inbound_flight_date_time AS TIMESTAMP)
                END AS inbound_flight_date_time_final,
                CASE
                    WHEN q1.outbound_flight_date_time IS NOT NULL AND q1.outbound_flight_date_time_sto IS NULL THEN CAST(q1.outbound_flight_date_time AS TIMESTAMP)
                    WHEN q1.outbound_flight_date_time IS NULL AND q1.outbound_flight_date_time_sto IS NOT NULL THEN q1.outbound_flight_date_time_sto
                    ELSE CAST(q1.outbound_flight_date_time AS TIMESTAMP)
                END AS outbound_flight_date_time_final,
                CASE
                    WHEN q1.inbound_gate IS NOT NULL AND q1.inbound_gate_sto IS NULL THEN q1.inbound_gate
                    WHEN q1.inbound_gate IS NULL AND q1.inbound_gate_sto IS NOT NULL THEN q1.inbound_gate_sto
                    ELSE q1.inbound_gate
                END AS inbound_gate_final,
                CASE
                    WHEN q1.outbound_gate IS NOT NULL AND q1.outbound_gate_sto IS NULL THEN q1.outbound_gate
                    WHEN q1.outbound_gate IS NULL AND q1.outbound_gate_sto IS NOT NULL THEN q1.outbound_gate_sto
                    ELSE q1.outbound_gate
                END AS outbound_gate_final,
            q1.hash,
            q1.bhs_pk,
            q1.message,
            q1.message_type,
            q1.bsm_chg_del,
            q1.`[.V/] Version and Supplementary Data`,
            q1.`[.K/] Default Message Printer`,
            q1.`[.J/] Processing Information`,
            q1.`[.I/] Inbound Flight Information`,
            q1.`[.F/] Outbound Flight Information`,
            q1.`[.O/] Onward Flight Information`,
            q1.inbound_flight_number,
            q1.inbound_flight_date_txt,
            q1.inbound_flight_date,
            q1.inbound_departure_airport,
            q1.inbound_booking_class,
            q1.outbound_flight_number,
            q1.outbound_flight_date_txt,
            q1.outbound_flight_date,
            q1.outbound_departure_airport,
            q1.outbound_booking_class,
            q1.onward_flight_number,
            q1.onward_flight_date_txt,
            q1.onward_flight_date,
            q1.onward_departure_airport,
            q1.onward_booking_class,
            q1.`[.U/] Loading Data`,
            q1.`[.N/] Baggage Tag Details`,
            q1.`[.B/] Baggage Irregularities`,
            q1.`[.Q/] Load Sequence Number`,
            q1.`[.S/] Reconciliation Data`,
            q1.`[.P/] Passenger Name`,
            q1.`[.Y/] Frequent Traveller Number`,
            q1.`[.C/] Corporate Or Group Name`,
            q1.`[.L/] Automated PNR Address`,
            q1.`[.E/] Baggage Exception Data`,
            q1.`[.R/] Internal Airline Data`,
            q1.`[.X/] Baggage Security Screening`,
            q1.`[.T/] Baggage Tag Printer ID`,
            q1.`[.A/] Baggage Routing Information `,
            q1.`[.D/] Departure Airport / Date Info`,
            q1.`[.M/] Manual Tag Indicator`,
            q1.`[.H/] Handling Information`,
            q1.`[.W/] Pieces And Weight Data`,
            q1.weight_first_c,
            q1.weight_pieces,
            q1.`weight(kg)`,
            q1.idevent,
            q1.key,
            q1.eventts,
            q1.insertts,
            q1.eventtime,
            q1.upsert_time,
            q1.passive,
            q1.gpid,
            q1.outbound_flight_number_orj,
            q1.oub_airline_iata,
            q1.oub_remaining_part,
            q1.oub_flight_number,
            q1.inbound_flight_number_orj,
            q1.inb_airline_iata,
            q1.inb_remaining_part,
            q1.inb_flight_number,
            q1.inb_flight_nature,
            q1.inb_international_status,
            q1.out_flight_nature,
            q1.out_international_status,
            q1.inb_sto_flight_nature,
            q1.inb_sto_international_status,
            q1.outb_sto_flight_nature,
            q1.outb_sto_international_status,
            q1.inbound_flight_date_time,
            q1.outbound_flight_date_time,
            q1.inbound_flight_date_time_sto,
            q1.outbound_flight_date_time_sto,
            q1.inb_aircraft_iata,
            q1.inb_aircraft_icao,
            q1.inb_registration,
            q1.inb_pax,
            q1.inb_max_pax,
            q1.inb_pax_out,
            q1.inb_booked_pax,
            q1.inb_baggage_in,
            q1.inb_baggage_out,
            q1.inb_baggage_trans,
            q1.inb_cargo_in,
            q1.inb_cargo_out,
            q1.inb_cargo_trans,
            q1.outb_aircraft_iata,
            q1.outb_aircraft_icao,
            q1.outb_registration,
            q1.outb_pax,
            q1.outb_max_pax,
            q1.outb_pax_out,
            q1.outb_booked_pax,
            q1.outb_baggage_in,
            q1.outb_baggage_out,
            q1.outb_baggage_trans,
            q1.outb_cargo_in,
            q1.outb_cargo_out,
            q1.outb_cargo_trans,
            q1.inbound_gate,
            q1.outbound_gate,
            q1.inbound_gate_sto,
            q1.outbound_gate_sto,
            q1.inb_ams_groundservices,
            q1.inb_ams_p_pax,
            q1.inb_ams_body_type,
            q1.outb_ams_groundservices,
            q1.outb_ams_p_pax,
            q1.outb_ams_body_type,
            q1.ecac,
            q1.outbound_departure_country_tr,
            q1.outbound_departure_city_tr,
            q1.outbound_departure_city,
            q1.outbound_departure_country,
            q1.outbound_departure_country_latitude,
            q1.outbound_departure_country_longitude,
            q1.outbound_departure_airport_name,
            q1.inbound_country_tr,
            q1.inbound_city_tr,
            q1.inbound_city,
            q1.inbound_country,
            q1.inbound_country_latitude,
            q1.inbound_country_longitude,
            q1.inbound_departure_airport_name,
            q1.inbound_ticari_yolcu_sayisi,
            q1.outbound_ticari_yolcu_sayisi,
            q1.bhs_passenger_uniq,
            q1.bhs_passenger_family_4dep,
            q1.bhs_passenger_together_reservation_id,
            q1.bhs_passenger_together_baggage_id,
            q1.bhs_baggage_uniq,
            q1.outbound_gate_grup,
            q1.inbound_gate_grup,
            q1.inbound_outbound_gate_grup,
            q1.inbound_outbound_airport_route,
            q1.inbound_outbound_country_city_route,
            q1.ecac_passenger_uniq,
            q1.version1,
            q1.version2,
            q1.version3,
            q1.od_median_duration_interval,
            q1.estimated_departure_fromorg,
            q1.estimated_arrival,
            q1.is_nextday
           FROM ( SELECT v.od_median_duration_interval,
                    v.estimated_departure_fromorg,
                    v.estimated_arrival,
                    v.is_nextday,
                    v.hash,
                    v.bhs_pk,
                    v.message,
                    v.message_type,
                    v.bsm_chg_del,
                    v.`[.V/] Version and Supplementary Data`,
                    v.`[.K/] Default Message Printer`,
                    v.`[.J/] Processing Information`,
                    v.`[.I/] Inbound Flight Information`,
                    v.`[.F/] Outbound Flight Information`,
                    v.`[.O/] Onward Flight Information`,
                    v.inbound_flight_number,
                    v.inbound_flight_date_txt,
                    v.inbound_flight_date,
                    v.inbound_departure_airport,
                    v.inbound_booking_class,
                    v.outbound_flight_number,
                    v.outbound_flight_date_txt,
                    v.outbound_flight_date,
                    v.outbound_departure_airport,
                    v.outbound_booking_class,
                    v.onward_flight_number,
                    v.onward_flight_date_txt,
                    v.onward_flight_date,
                    v.onward_departure_airport,
                    v.onward_booking_class,
                    v.`[.U/] Loading Data`,
                    v.`[.N/] Baggage Tag Details`,
                    v.`[.B/] Baggage Irregularities`,
                    v.`[.Q/] Load Sequence Number`,
                    v.`[.S/] Reconciliation Data`,
                    v.`[.P/] Passenger Name`,
                    v.`[.Y/] Frequent Traveller Number`,
                    v.`[.C/] Corporate Or Group Name`,
                    v.`[.L/] Automated PNR Address`,
                    v.`[.E/] Baggage Exception Data`,
                    v.`[.R/] Internal Airline Data`,
                    v.`[.X/] Baggage Security Screening`,
                    v.`[.T/] Baggage Tag Printer ID`,
                    v.`[.A/] Baggage Routing Information `,
                    v.`[.D/] Departure Airport / Date Info`,
                    v.`[.M/] Manual Tag Indicator`,
                    v.`[.H/] Handling Information`,
                    v.`[.W/] Pieces And Weight Data`,
                    v.weight_first_c,
                    v.weight_pieces,
                    v.`weight(kg)`,
                    v.idevent,
                    v.key,
                    v.eventts,
                    v.insertts,
                    v.eventtime,
                    v.upsert_time,
                    v.passive,
                    v.gpid,
                    v.outbound_flight_number AS outbound_flight_number_orj,
                    v.oub_airline_iata,
                    v.oub_remaining_part,
                    v.oub_flight_number,
                    v.inbound_flight_number AS inbound_flight_number_orj,
                    v.inb_airline_iata,
                    v.inb_remaining_part,
                    v.inb_flight_number,
                    inb.flight_nature AS inb_flight_nature,
                    inb.international_status AS inb_international_status,
                    outb.flight_nature AS out_flight_nature,
                    outb.international_status AS out_international_status,
                    inb_sto.`4zucs_ad03_flight_nature` AS inb_sto_flight_nature,
                    inb_sto.`4zucs_ad03_int_status` AS inb_sto_international_status,
                    outb_sto.`4zucs_ad03_flight_nature` AS outb_sto_flight_nature,
                    outb_sto.`4zucs_ad03_int_status` AS outb_sto_international_status,
                    CAST(concat(CAST(inb.atad_date_time AS STRING), ' ', substring(CAST(inb.atad_time AS STRING), 12, 8)) AS TIMESTAMP) AS inbound_flight_date_time,
                    CAST(concat(CAST(outb.atad_date_time AS STRING), ' ', substring(CAST(outb.atad_time AS STRING), 12, 8)) AS TIMESTAMP) AS outbound_flight_date_time,
                    CAST(concat(inb_sto.v_sto_date, ' ', inb_sto.v_sto_time_gmt3) AS TIMESTAMP) AS inbound_flight_date_time_sto,
                    CAST(concat(outb_sto.v_sto_date, ' ', outb_sto.v_sto_time_gmt3) AS TIMESTAMP) AS outbound_flight_date_time_sto,
                    inb.aircraft_iata AS inb_aircraft_iata,
                    inb.aircraft_icao AS inb_aircraft_icao,
                    inb.registration AS inb_registration,
                    inb.pax AS inb_pax,
                    inb.max_pax AS inb_max_pax,
                    inb.pax_out AS inb_pax_out,
                    inb.booked_pax AS inb_booked_pax,
                    inb.baggage_in AS inb_baggage_in,
                    inb.baggage_out AS inb_baggage_out,
                    inb.baggage_trans AS inb_baggage_trans,
                    inb.cargo_in AS inb_cargo_in,
                    inb.cargo_out AS inb_cargo_out,
                    inb.cargo_trans AS inb_cargo_trans,
                    outb.aircraft_iata AS outb_aircraft_iata,
                    outb.aircraft_icao AS outb_aircraft_icao,
                    outb.registration AS outb_registration,
                    outb.pax AS outb_pax,
                    outb.max_pax AS outb_max_pax,
                    outb.pax_out AS outb_pax_out,
                    outb.booked_pax AS outb_booked_pax,
                    outb.baggage_in AS outb_baggage_in,
                    outb.baggage_out AS outb_baggage_out,
                    outb.baggage_trans AS outb_baggage_trans,
                    outb.cargo_in AS outb_cargo_in,
                    outb.cargo_out AS outb_cargo_out,
                    outb.cargo_trans AS outb_cargo_trans,
                    inb.stand AS inbound_gate,
                    outb.gate AS outbound_gate,
                    inb_sto.v_gate AS inbound_gate_sto,
                    outb_sto.v_gate AS outbound_gate_sto,
                    inb_sto.`GroundServices` AS inb_ams_groundservices,
                    inb_sto.p_pax AS inb_ams_p_pax,
                    inb_sto.v_body_type AS inb_ams_body_type,
                    outb_sto.`GroundServices` AS outb_ams_groundservices,
                    outb_sto.p_pax AS outb_ams_p_pax,
                    outb_sto.v_body_type AS outb_ams_body_type,
                    iad.ecac,
                    oad.`Country (TURKISH) ` AS outbound_departure_country_tr,
                    oad.`City (TURKISH)` AS outbound_departure_city_tr,
                    oad.city AS outbound_departure_city,
                    oad.country AS outbound_departure_country,
                    oad.country_latitude AS outbound_departure_country_latitude,
                    oad.country_longitude AS outbound_departure_country_longitude,
                    oad.`Name` AS outbound_departure_airport_name,
                    iad.`Country (TURKISH) ` AS inbound_country_tr,
                    iad.`City (TURKISH)` AS inbound_city_tr,
                    iad.city AS inbound_city,
                    iad.country AS inbound_country,
                    iad.country_latitude AS inbound_country_latitude,
                    iad.country_longitude AS inbound_country_longitude,
                    iad.`Name` AS inbound_departure_airport_name,
                        CASE
                            WHEN dayofmonth(to_date(inb.sto_date)) <= 10 AND inb.landtakeoffdate_date >= date_trunc('month', add_months(to_date(inb.sto_date), -1)) AND (COALESCE(inb.dom2dom, 0) + COALESCE(inb.dom2int, 0) + COALESCE(inb.int2dom, 0) + COALESCE(inb.int2int, 0) + COALESCE(inb.pax_in, 0) + COALESCE(inb.pax_out, 0) + COALESCE(inb.transit_pax, 0)) = 0 AND inb.service_type = 'J' THEN COALESCE(inb.booked_pax, 0)
                            WHEN dayofmonth(to_date(inb.sto_date)) > 10 AND inb.landtakeoffdate_date >= date_trunc('month', to_date(inb.sto_date)) AND (COALESCE(inb.dom2dom, 0) + COALESCE(inb.dom2int, 0) + COALESCE(inb.int2dom, 0) + COALESCE(inb.int2int, 0) + COALESCE(inb.pax_in, 0) + COALESCE(inb.pax_out, 0) + COALESCE(inb.transit_pax, 0)) = 0 AND inb.service_type = 'J' THEN COALESCE(inb.booked_pax, 0)
                            ELSE COALESCE(inb.dom2dom, 0) + COALESCE(inb.dom2int, 0) + COALESCE(inb.int2dom, 0) + COALESCE(inb.int2int, 0) + COALESCE(inb.pax_in, 0) + COALESCE(inb.pax_out, 0) + COALESCE(inb.transit_pax, 0)
                        END AS inbound_ticari_yolcu_sayisi,
                        CASE
                            WHEN dayofmonth(to_date(outb.sto_date)) <= 10 AND outb.landtakeoffdate_date >= date_trunc('month', add_months(to_date(outb.sto_date), -1)) AND (COALESCE(outb.dom2dom, 0) + COALESCE(outb.dom2int, 0) + COALESCE(outb.int2dom, 0) + COALESCE(outb.int2int, 0) + COALESCE(outb.pax_in, 0) + COALESCE(outb.pax_out, 0) + COALESCE(outb.transit_pax, 0)) = 0 AND outb.service_type = 'J' THEN COALESCE(outb.booked_pax, 0)
                            WHEN dayofmonth(to_date(outb.sto_date)) > 10 AND outb.landtakeoffdate_date >= date_trunc('month', to_date(outb.sto_date)) AND (COALESCE(outb.dom2dom, 0) + COALESCE(outb.dom2int, 0) + COALESCE(outb.int2dom, 0) + COALESCE(outb.int2int, 0) + COALESCE(outb.pax_in, 0) + COALESCE(outb.pax_out, 0) + COALESCE(outb.transit_pax, 0)) = 0 AND outb.service_type = 'J' THEN COALESCE(outb.booked_pax, 0)
                            ELSE COALESCE(outb.dom2dom, 0) + COALESCE(outb.dom2int, 0) + COALESCE(outb.int2dom, 0) + COALESCE(outb.int2int, 0) + COALESCE(outb.pax_in, 0) + COALESCE(outb.pax_out, 0) + COALESCE(outb.transit_pax, 0)
                        END AS outbound_ticari_yolcu_sayisi,
                        CASE
                            WHEN COALESCE(v.`[.P/] Passenger Name`, '') <> '' THEN concat_ws('|', replace(date_format(COALESCE(v.inbound_flight_date, CAST('1900-01-01' AS DATE)), 'yyyyMMdd'), '19000101', '00000000'), concat(regexp_replace(COALESCE(COALESCE(v.inb_flight_number, '00000000'), ''), '[0-9]+$', ''),
                            CASE
                                WHEN length(regexp_replace(COALESCE(COALESCE(v.inb_flight_number, '00000000'), ''), '[^0-9]', '', 'g')) < 4 THEN lpad(regexp_replace(COALESCE(COALESCE(v.inb_flight_number, '00000000'), ''), '[^0-9]', ''), 4, '0')
                                ELSE regexp_replace(COALESCE(COALESCE(v.inb_flight_number, '00000000'), ''), '[^0-9]', '')
                            END), replace(date_format(COALESCE(v.outbound_flight_date, CAST('1900-01-01' AS DATE)), 'yyyyMMdd'), '19000101', '00000000'), concat(regexp_replace(COALESCE(COALESCE(v.oub_flight_number, '00000000'), ''), '[0-9]+$', ''),
                            CASE
                                WHEN length(regexp_replace(COALESCE(COALESCE(v.oub_flight_number, '00000000'), ''), '[^0-9]', '')) < 4 THEN lpad(regexp_replace(COALESCE(COALESCE(v.oub_flight_number, '00000000'), ''), '[^0-9]', ''), 4, '0')
                                ELSE regexp_replace(COALESCE(COALESCE(v.oub_flight_number, '00000000'), ''), '[^0-9]', '')
                            END), COALESCE(v.`[.P/] Passenger Name`, ''))
                            ELSE NULL
                        END AS bhs_passenger_uniq,
                        CASE
                            WHEN COALESCE(v.`[.P/] Passenger Name`, '') <> '' AND COALESCE(v.`[.L/] Automated PNR Address`, '') <> '' AND COALESCE(v.oub_flight_number, '') <> '' THEN concat(split(COALESCE(v.`[.P/] Passenger Name`, ''), '/')[0], '/', COALESCE(v.oub_flight_number, ''), '/', COALESCE(v.outbound_flight_date, CAST('2000-01-01' AS DATE)), '/', COALESCE(v.`[.L/] Automated PNR Address`, ''))
                            ELSE NULL
                        END AS bhs_passenger_family_4dep,
                        CASE
                            WHEN COALESCE(v.`[.L/] Automated PNR Address`, '') <> '' AND length(COALESCE(v.`[.L/] Automated PNR Address`, '')) = 6 THEN concat(COALESCE(v.oub_flight_number, ''), '/', COALESCE(v.outbound_flight_date, CAST('2000-01-01' AS DATE)), '/', COALESCE(v.`[.L/] Automated PNR Address`, ''))
                            ELSE NULL
                        END AS bhs_passenger_together_reservation_id,
                        CASE
                            WHEN COALESCE(v.`[.N/] Baggage Tag Details`, '') <> '' AND length(COALESCE(v.`[.N/] Baggage Tag Details`, '')) = 13 THEN concat(COALESCE(v.oub_flight_number, ''), '/', COALESCE(v.outbound_flight_date, CAST('2000-01-01' AS DATE)), '/', COALESCE(v.`[.N/] Baggage Tag Details`, ''))
                            ELSE NULL
                        END AS bhs_passenger_together_baggage_id,
                        CASE
                            WHEN COALESCE(v.`[.N/] Baggage Tag Details`, '') <> '' THEN concat_ws('|', replace(date_format(COALESCE(v.inbound_flight_date, CAST('1900-01-01' AS DATE)), 'yyyyMMdd'), '19000101', '00000000'), concat(regexp_replace(COALESCE(COALESCE(v.inbound_flight_number, '00000000'), ''), '[0-9]+$', ''),
                            CASE
                                WHEN length(regexp_replace(COALESCE(COALESCE(v.inbound_flight_number, '00000000'), ''), '[^0-9]', '')) < 4 THEN lpad(regexp_replace(COALESCE(COALESCE(v.inbound_flight_number, '00000000'), ''), '[^0-9]', ''), 4, '0')
                                ELSE regexp_replace(COALESCE(COALESCE(v.inbound_flight_number, '00000000'), ''), '[^0-9]', '')
                            END), replace(date_format(COALESCE(v.outbound_flight_date, CAST('1900-01-01' AS DATE)), 'yyyyMMdd'), '19000101', '00000000'), concat(regexp_replace(COALESCE(COALESCE(v.outbound_flight_number, '00000000'), ''), '[0-9]+$', ''),
                            CASE
                                WHEN length(regexp_replace(COALESCE(COALESCE(v.outbound_flight_number, '00000000'), ''), '[^0-9]', '')) < 4 THEN lpad(regexp_replace(COALESCE(COALESCE(v.outbound_flight_number, '00000000'), ''), '[^0-9]', ''), 4, '0')
                                ELSE regexp_replace(COALESCE(COALESCE(v.outbound_flight_number, '00000000'), ''), '[^0-9]', '')
                            END), v.`[.N/] Baggage Tag Details`)
                            ELSE NULL
                        END AS bhs_baggage_uniq,
                    left(outb.gate, 1) AS outbound_gate_grup,
                    left(inb.stand, 1) AS inbound_gate_grup,
                    concat(left(COALESCE(inb.stand, ''), 1), '/', left(COALESCE(outb.gate, ''), 1)) AS inbound_outbound_gate_grup,
                    concat(COALESCE(iad.`Name`, ''), '/', 'IST', '/', COALESCE(oad.`Name`, '')) AS inbound_outbound_airport_route,
                    concat(COALESCE(iad.country, ''), '/', COALESCE(iad.city, ''), '/', 'IST', '/', COALESCE(oad.country, ''), '/', COALESCE(oad.city, '')) AS inbound_outbound_country_city_route,
                        CASE
                            WHEN iad.ecac = 'ECAC' THEN concat(v.`[.P/] Passenger Name`, COALESCE(v.outbound_flight_number, ''), CAST(v.outbound_flight_date AS STRING), COALESCE(v.inbound_flight_number, ''), CAST(v.inbound_flight_date AS STRING))
                            ELSE NULL
                        END AS ecac_passenger_uniq,
                    substring(v.`[.V/] Version and Supplementary Data`, 1, 1) AS version1,
                    substring(v.`[.V/] Version and Supplementary Data`, 2, 1) AS version2,
                    substring(v.`[.V/] Version and Supplementary Data`, 3) AS version3
                   FROM ( SELECT od.median_duration_interval AS od_median_duration_interval,
                            from_utc_timestamp(b.eventts, 'Europe/Istanbul') + interval 30 minutes AS estimated_departure_fromorg,
                                CASE
                                    WHEN CAST(od.median_duration_interval + from_utc_timestamp(b.eventts, 'Europe/Istanbul') + interval 30 minutes AS DATE) <> b.inbound_flight_date THEN od.median_duration_interval + from_utc_timestamp(b.eventts, 'Europe/Istanbul') + interval 30 minutes
                                    ELSE CAST(b.inbound_flight_date AS TIMESTAMP)
                                END AS estimated_arrival,
                                CASE
                                    WHEN CAST(od.median_duration_interval + from_utc_timestamp(b.eventts, 'Europe/Istanbul') + interval 30 minutes AS DATE) <> b.inbound_flight_date THEN CAST(od.median_duration_interval + from_utc_timestamp(b.eventts, 'Europe/Istanbul') + interval 30 minutes AS DATE)
                                    ELSE b.inbound_flight_date
                                END AS inbound_flight_date,
                                CASE
                                    WHEN CAST(od.median_duration_interval + from_utc_timestamp(b.eventts, 'Europe/Istanbul') + interval 30 minutes AS DATE) <> b.inbound_flight_date THEN 'next_day'
                                    ELSE NULL
                                END AS is_nextday,
                            b.hash,
                            b.bhs_pk,
                            b.message,
                            b.message_type,
                            b.bsm_chg_del,
                            b.`[.V/] Version and Supplementary Data`,
                            b.`[.K/] Default Message Printer`,
                            b.`[.J/] Processing Information`,
                            b.`[.I/] Inbound Flight Information`,
                            b.`[.F/] Outbound Flight Information`,
                            b.`[.O/] Onward Flight Information`,
                            b.inbound_flight_number,
                            b.inbound_flight_date_txt,
                            b.inbound_departure_airport,
                            b.inbound_booking_class,
                            b.outbound_flight_number,
                            b.outbound_flight_date_txt,
                            b.outbound_flight_date,
                            b.outbound_departure_airport,
                            b.outbound_booking_class,
                            b.onward_flight_number,
                            b.onward_flight_date_txt,
                            b.onward_flight_date,
                            b.onward_departure_airport,
                            b.onward_booking_class,
                            b.`[.U/] Loading Data`,
                            b.`[.N/] Baggage Tag Details`,
                            b.`[.B/] Baggage Irregularities`,
                            b.`[.Q/] Load Sequence Number`,
                            b.`[.S/] Reconciliation Data`,
                            b.`[.P/] Passenger Name`,
                            b.`[.Y/] Frequent Traveller Number`,
                            b.`[.C/] Corporate Or Group Name`,
                            b.`[.L/] Automated PNR Address`,
                            b.`[.E/] Baggage Exception Data`,
                            b.`[.R/] Internal Airline Data`,
                            b.`[.X/] Baggage Security Screening`,
                            b.`[.T/] Baggage Tag Printer ID`,
                            b.`[.A/] Baggage Routing Information `,
                            b.`[.D/] Departure Airport / Date Info`,
                            b.`[.M/] Manual Tag Indicator`,
                            b.`[.H/] Handling Information`,
                            b.`[.W/] Pieces And Weight Data`,
                            b.weight_first_c,
                            b.weight_pieces,
                            b.`weight(kg)`,
                            b.idevent,
                            b.key,
                            b.eventts,
                            b.insertts,
                            b.eventtime,
                            b.upsert_time,
                            b.passive,
                            b.gpid,
                            b.outbound_flight_number_orj,
                            b.oub_airline_iata,
                            b.oub_remaining_part,
                            b.oub_flight_number,
                            b.inbound_flight_number_orj,
                            b.inb_airline_iata,
                            b.inb_remaining_part,
                            b.inb_flight_number
                           FROM stg.bhs_bsm_inc b
                             LEFT JOIN ods.dim_od_flight_duration od ON b.inbound_departure_airport = CAST(od.origin_iata AS STRING) AND CAST(od.dest_iata AS STRING) = 'IST') v
                     LEFT JOIN ( SELECT concat(btrim(sapisp_zbiiga_cv233.airline_iata), CAST(NULLIF(regexp_replace(substring(sapisp_zbiiga_cv233.flight_number, length(sapisp_zbiiga_cv233.airline_iata) + 1), '[^0-9]', ''), '') AS INT)) AS flight_number_final,
                            sapisp_zbiiga_cv233.mandt,
                            sapisp_zbiiga_cv233.airline_iata,
                            sapisp_zbiiga_cv233.flight_nature,
                            sapisp_zbiiga_cv233.flight_number,
                            sapisp_zbiiga_cv233.sto_date,
                            sapisp_zbiiga_cv233.sto_date_time,
                            sapisp_zbiiga_cv233.sto_dt,
                            sapisp_zbiiga_cv233.international_status,
                            sapisp_zbiiga_cv233.operational_status,
                            sapisp_zbiiga_cv233.link_international_status,
                            sapisp_zbiiga_cv233.unique_flight_identifier,
                            sapisp_zbiiga_cv233.link_aipunique_id,
                            sapisp_zbiiga_cv233.link_flight_nature,
                            sapisp_zbiiga_cv233.link_sto_date,
                            sapisp_zbiiga_cv233.link_sto_date_time,
                            sapisp_zbiiga_cv233.link_airline_iata,
                            sapisp_zbiiga_cv233.link_flightcode,
                            sapisp_zbiiga_cv233.sto_time,
                            sapisp_zbiiga_cv233.registration,
                            sapisp_zbiiga_cv233.name,
                            sapisp_zbiiga_cv233.service_type,
                            sapisp_zbiiga_cv233.fservicetype,
                            sapisp_zbiiga_cv233.aircraft_iata,
                            sapisp_zbiiga_cv233.aircraft_icao,
                            sapisp_zbiiga_cv233.destination_iata,
                            sapisp_zbiiga_cv233.destination_icao,
                            sapisp_zbiiga_cv233.destination_name,
                            sapisp_zbiiga_cv233.destination_country,
                            sapisp_zbiiga_cv233.origin_iata,
                            sapisp_zbiiga_cv233.origin_icao,
                            sapisp_zbiiga_cv233.origin_name,
                            sapisp_zbiiga_cv233.origin_city,
                            sapisp_zbiiga_cv233.deleted,
                            sapisp_zbiiga_cv233.flight_suffix,
                            sapisp_zbiiga_cv233.mto,
                            sapisp_zbiiga_cv233.iata,
                            sapisp_zbiiga_cv233.atad_date,
                            sapisp_zbiiga_cv233.atad_date_time,
                            sapisp_zbiiga_cv233.atad_time,
                            sapisp_zbiiga_cv233.etad_date,
                            sapisp_zbiiga_cv233.etad_date_time,
                            sapisp_zbiiga_cv233.etad_time,
                            sapisp_zbiiga_cv233.max_pax,
                            sapisp_zbiiga_cv233.unique_id,
                            sapisp_zbiiga_cv233.dep_iata,
                            sapisp_zbiiga_cv233.arr_iata,
                            sapisp_zbiiga_cv233.dep_icao,
                            sapisp_zbiiga_cv233.arr_icao,
                            sapisp_zbiiga_cv233.dep_name,
                            sapisp_zbiiga_cv233.arr_name,
                            sapisp_zbiiga_cv233.stand,
                            sapisp_zbiiga_cv233.gate,
                            sapisp_zbiiga_cv233.landtakeofftime,
                            sapisp_zbiiga_cv233.inoutblocktime,
                            sapisp_zbiiga_cv233.tarih,
                            sapisp_zbiiga_cv233.atad_tarihi,
                            sapisp_zbiiga_cv233.ay_txt,
                            sapisp_zbiiga_cv233.yil,
                            sapisp_zbiiga_cv233.ay,
                            sapisp_zbiiga_cv233.year_int,
                            sapisp_zbiiga_cv233.quarter_int,
                            sapisp_zbiiga_cv233.month_int,
                            sapisp_zbiiga_cv233.day_int,
                            sapisp_zbiiga_cv233.landtakeoffdate,
                            sapisp_zbiiga_cv233.landtakeoffdate_date,
                            sapisp_zbiiga_cv233.name1,
                            sapisp_zbiiga_cv233.en_son_tarih,
                            sapisp_zbiiga_cv233.t002chdat,
                            sapisp_zbiiga_cv233.t003chdat,
                            sapisp_zbiiga_cv233.t008chdat,
                            sapisp_zbiiga_cv233.t009chdat,
                            sapisp_zbiiga_cv233.t0017chdat,
                            sapisp_zbiiga_cv233.t0014chdat,
                            sapisp_zbiiga_cv233.t0062chdat,
                            sapisp_zbiiga_cv233.time_interval,
                            sapisp_zbiiga_cv233.ga_name,
                            sapisp_zbiiga_cv233.planlanan_ucus_tarihi,
                            sapisp_zbiiga_cv233.runway,
                            sapisp_zbiiga_cv233.location,
                            sapisp_zbiiga_cv233.name_filter,
                            sapisp_zbiiga_cv233.atm,
                            sapisp_zbiiga_cv233.pax_in,
                            sapisp_zbiiga_cv233.pax_out,
                            sapisp_zbiiga_cv233.booked_pax,
                            sapisp_zbiiga_cv233.int2int,
                            sapisp_zbiiga_cv233.dom2int,
                            sapisp_zbiiga_cv233.int2dom,
                            sapisp_zbiiga_cv233.dom2dom,
                            sapisp_zbiiga_cv233.transfer_disi,
                            sapisp_zbiiga_cv233.pas_total_infant,
                            sapisp_zbiiga_cv233.pas_total_crew,
                            sapisp_zbiiga_cv233.pas_total_exempt,
                            sapisp_zbiiga_cv233.pas_total_military,
                            sapisp_zbiiga_cv233.dhc_in,
                            sapisp_zbiiga_cv233.dhc_out,
                            sapisp_zbiiga_cv233.baggage_in,
                            sapisp_zbiiga_cv233.baggage_out,
                            sapisp_zbiiga_cv233.baggage_trans,
                            sapisp_zbiiga_cv233.cargo_in,
                            sapisp_zbiiga_cv233.cargo_out,
                            sapisp_zbiiga_cv233.cargo_trans,
                            sapisp_zbiiga_cv233.mail_in,
                            sapisp_zbiiga_cv233.mail_out,
                            sapisp_zbiiga_cv233.infant_in,
                            sapisp_zbiiga_cv233.infant_out,
                            sapisp_zbiiga_cv233.other_exempted_in,
                            sapisp_zbiiga_cv233.other_exempted_out,
                            sapisp_zbiiga_cv233.taxitime,
                            sapisp_zbiiga_cv233.transit_pax,
                            sapisp_zbiiga_cv233.entegrasyon,
                            sapisp_zbiiga_cv233.rezervasyon,
                            sapisp_zbiiga_cv233.kapasite,
                            sapisp_zbiiga_cv233.pax,
                            sapisp_zbiiga_cv233.pax_avih_in,
                            sapisp_zbiiga_cv233.pax_avih_out,
                            sapisp_zbiiga_cv233.avih_int2int_in,
                            sapisp_zbiiga_cv233.avih_int2int_out,
                            sapisp_zbiiga_cv233.avih_dom2int_in,
                            sapisp_zbiiga_cv233.avih_dom2int_out,
                            sapisp_zbiiga_cv233.avih_int2dom_in,
                            sapisp_zbiiga_cv233.avih_int2dom_out,
                            sapisp_zbiiga_cv233.avih_dom2dom_in,
                            sapisp_zbiiga_cv233.avih_dom2dom_out,
                            sapisp_zbiiga_cv233.petc_in,
                            sapisp_zbiiga_cv233.petc_out,
                            sapisp_zbiiga_cv233.petc_int2int_in,
                            sapisp_zbiiga_cv233.petc_int2int_out,
                            sapisp_zbiiga_cv233.petc_dom2int_in,
                            sapisp_zbiiga_cv233.petc_dom2int_out,
                            sapisp_zbiiga_cv233.petc_int2dom_in,
                            sapisp_zbiiga_cv233.petc_int2dom_out,
                            sapisp_zbiiga_cv233.petc_dom2dom_in,
                            sapisp_zbiiga_cv233.petc_dom2dom_out,
                            sapisp_zbiiga_cv233.son_tarih,
                            sapisp_zbiiga_cv233.upsert_time,
                            sapisp_zbiiga_cv233.upsert_type
                           FROM stg.sapisp_zbiiga_cv233) inb ON v.inbound_flight_date = CAST(inb.sto_date AS DATE) AND v.inb_flight_number = inb.flight_number_final AND inb.flight_nature = 'ARRIVAL'
                     LEFT JOIN ( SELECT concat(btrim(sapisp_zbiiga_cv233.airline_iata), CAST(NULLIF(regexp_replace(substring(sapisp_zbiiga_cv233.flight_number, length(sapisp_zbiiga_cv233.airline_iata) + 1), '[^0-9]', ''), '') AS INT)) AS flight_number_final,
                            sapisp_zbiiga_cv233.mandt,
                            sapisp_zbiiga_cv233.airline_iata,
                            sapisp_zbiiga_cv233.flight_nature,
                            sapisp_zbiiga_cv233.flight_number,
                            sapisp_zbiiga_cv233.sto_date,
                            sapisp_zbiiga_cv233.sto_date_time,
                            sapisp_zbiiga_cv233.sto_dt,
                            sapisp_zbiiga_cv233.international_status,
                            sapisp_zbiiga_cv233.operational_status,
                            sapisp_zbiiga_cv233.link_international_status,
                            sapisp_zbiiga_cv233.unique_flight_identifier,
                            sapisp_zbiiga_cv233.link_aipunique_id,
                            sapisp_zbiiga_cv233.link_flight_nature,
                            sapisp_zbiiga_cv233.link_sto_date,
                            sapisp_zbiiga_cv233.link_sto_date_time,
                            sapisp_zbiiga_cv233.link_airline_iata,
                            sapisp_zbiiga_cv233.link_flightcode,
                            sapisp_zbiiga_cv233.sto_time,
                            sapisp_zbiiga_cv233.registration,
                            sapisp_zbiiga_cv233.name,
                            sapisp_zbiiga_cv233.service_type,
                            sapisp_zbiiga_cv233.fservicetype,
                            sapisp_zbiiga_cv233.aircraft_iata,
                            sapisp_zbiiga_cv233.aircraft_icao,
                            sapisp_zbiiga_cv233.destination_iata,
                            sapisp_zbiiga_cv233.destination_icao,
                            sapisp_zbiiga_cv233.destination_name,
                            sapisp_zbiiga_cv233.destination_country,
                            sapisp_zbiiga_cv233.origin_iata,
                            sapisp_zbiiga_cv233.origin_icao,
                            sapisp_zbiiga_cv233.origin_name,
                            sapisp_zbiiga_cv233.origin_city,
                            sapisp_zbiiga_cv233.deleted,
                            sapisp_zbiiga_cv233.flight_suffix,
                            sapisp_zbiiga_cv233.mto,
                            sapisp_zbiiga_cv233.iata,
                            sapisp_zbiiga_cv233.atad_date,
                            sapisp_zbiiga_cv233.atad_date_time,
                            sapisp_zbiiga_cv233.atad_time,
                            sapisp_zbiiga_cv233.etad_date,
                            sapisp_zbiiga_cv233.etad_date_time,
                            sapisp_zbiiga_cv233.etad_time,
                            sapisp_zbiiga_cv233.max_pax,
                            sapisp_zbiiga_cv233.unique_id,
                            sapisp_zbiiga_cv233.dep_iata,
                            sapisp_zbiiga_cv233.arr_iata,
                            sapisp_zbiiga_cv233.dep_icao,
                            sapisp_zbiiga_cv233.arr_icao,
                            sapisp_zbiiga_cv233.dep_name,
                            sapisp_zbiiga_cv233.arr_name,
                            sapisp_zbiiga_cv233.stand,
                            sapisp_zbiiga_cv233.gate,
                            sapisp_zbiiga_cv233.landtakeofftime,
                            sapisp_zbiiga_cv233.inoutblocktime,
                            sapisp_zbiiga_cv233.tarih,
                            sapisp_zbiiga_cv233.atad_tarihi,
                            sapisp_zbiiga_cv233.ay_txt,
                            sapisp_zbiiga_cv233.yil,
                            sapisp_zbiiga_cv233.ay,
                            sapisp_zbiiga_cv233.year_int,
                            sapisp_zbiiga_cv233.quarter_int,
                            sapisp_zbiiga_cv233.month_int,
                            sapisp_zbiiga_cv233.day_int,
                            sapisp_zbiiga_cv233.landtakeoffdate,
                            sapisp_zbiiga_cv233.landtakeoffdate_date,
                            sapisp_zbiiga_cv233.name1,
                            sapisp_zbiiga_cv233.en_son_tarih,
                            sapisp_zbiiga_cv233.t002chdat,
                            sapisp_zbiiga_cv233.t003chdat,
                            sapisp_zbiiga_cv233.t008chdat,
                            sapisp_zbiiga_cv233.t009chdat,
                            sapisp_zbiiga_cv233.t0017chdat,
                            sapisp_zbiiga_cv233.t0014chdat,
                            sapisp_zbiiga_cv233.t0062chdat,
                            sapisp_zbiiga_cv233.time_interval,
                            sapisp_zbiiga_cv233.ga_name,
                            sapisp_zbiiga_cv233.planlanan_ucus_tarihi,
                            sapisp_zbiiga_cv233.runway,
                            sapisp_zbiiga_cv233.location,
                            sapisp_zbiiga_cv233.name_filter,
                            sapisp_zbiiga_cv233.atm,
                            sapisp_zbiiga_cv233.pax_in,
                            sapisp_zbiiga_cv233.pax_out,
                            sapisp_zbiiga_cv233.booked_pax,
                            sapisp_zbiiga_cv233.int2int,
                            sapisp_zbiiga_cv233.dom2int,
                            sapisp_zbiiga_cv233.int2dom,
                            sapisp_zbiiga_cv233.dom2dom,
                            sapisp_zbiiga_cv233.transfer_disi,
                            sapisp_zbiiga_cv233.pas_total_infant,
                            sapisp_zbiiga_cv233.pas_total_crew,
                            sapisp_zbiiga_cv233.pas_total_exempt,
                            sapisp_zbiiga_cv233.pas_total_military,
                            sapisp_zbiiga_cv233.dhc_in,
                            sapisp_zbiiga_cv233.dhc_out,
                            sapisp_zbiiga_cv233.baggage_in,
                            sapisp_zbiiga_cv233.baggage_out,
                            sapisp_zbiiga_cv233.baggage_trans,
                            sapisp_zbiiga_cv233.cargo_in,
                            sapisp_zbiiga_cv233.cargo_out,
                            sapisp_zbiiga_cv233.cargo_trans,
                            sapisp_zbiiga_cv233.mail_in,
                            sapisp_zbiiga_cv233.mail_out,
                            sapisp_zbiiga_cv233.infant_in,
                            sapisp_zbiiga_cv233.infant_out,
                            sapisp_zbiiga_cv233.other_exempted_in,
                            sapisp_zbiiga_cv233.other_exempted_out,
                            sapisp_zbiiga_cv233.taxitime,
                            sapisp_zbiiga_cv233.transit_pax,
                            sapisp_zbiiga_cv233.entegrasyon,
                            sapisp_zbiiga_cv233.rezervasyon,
                            sapisp_zbiiga_cv233.kapasite,
                            sapisp_zbiiga_cv233.pax,
                            sapisp_zbiiga_cv233.pax_avih_in,
                            sapisp_zbiiga_cv233.pax_avih_out,
                            sapisp_zbiiga_cv233.avih_int2int_in,
                            sapisp_zbiiga_cv233.avih_int2int_out,
                            sapisp_zbiiga_cv233.avih_dom2int_in,
                            sapisp_zbiiga_cv233.avih_dom2int_out,
                            sapisp_zbiiga_cv233.avih_int2dom_in,
                            sapisp_zbiiga_cv233.avih_int2dom_out,
                            sapisp_zbiiga_cv233.avih_dom2dom_in,
                            sapisp_zbiiga_cv233.avih_dom2dom_out,
                            sapisp_zbiiga_cv233.petc_in,
                            sapisp_zbiiga_cv233.petc_out,
                            sapisp_zbiiga_cv233.petc_int2int_in,
                            sapisp_zbiiga_cv233.petc_int2int_out,
                            sapisp_zbiiga_cv233.petc_dom2int_in,
                            sapisp_zbiiga_cv233.petc_dom2int_out,
                            sapisp_zbiiga_cv233.petc_int2dom_in,
                            sapisp_zbiiga_cv233.petc_int2dom_out,
                            sapisp_zbiiga_cv233.petc_dom2dom_in,
                            sapisp_zbiiga_cv233.petc_dom2dom_out,
                            sapisp_zbiiga_cv233.son_tarih,
                            sapisp_zbiiga_cv233.upsert_time,
                            sapisp_zbiiga_cv233.upsert_type
                           FROM stg.sapisp_zbiiga_cv233) outb ON v.outbound_flight_date = CAST(outb.sto_date AS DATE) AND v.oub_flight_number = outb.flight_number_final AND outb.flight_nature = 'DEPARTURE'
                     LEFT JOIN ( SELECT ams_flight_data_old._id,
                            ams_flight_data_old.`4zucs_ad03_airline_iata`,
                            ams_flight_data_old.`4zucs_ad03_destination_iata`,
                            ams_flight_data_old.`4zucs_ad03_origin_city`,
                            ams_flight_data_old.origin_iata,
                            ams_flight_data_old.`4zucs_ad03_flight_nature`,
                            ams_flight_data_old.`4zucs_ad03_actual_flight_number`,
                            ams_flight_data_old.v_sto_time_gmt3,
                            ams_flight_data_old.v_sto_date,
                            ams_flight_data_old.city,
                            ams_flight_data_old.`InBlock`,
                            ams_flight_data_old.landing,
                            ams_flight_data_old.`4zucs_ad03_service_type`,
                            ams_flight_data_old.`4zucs_ad03_int_status`,
                            ams_flight_data_old.`4zucs_ad03_registration`,
                            ams_flight_data_old.p_max_pax,
                            ams_flight_data_old.v_max_pax,
                            ams_flight_data_old.v_bay,
                            ams_flight_data_old.identifier,
                            ams_flight_data_old.code,
                            ams_flight_data_old.op_status,
                            ams_flight_data_old.callsign,
                            ams_flight_data_old.link_atad_date,
                            ams_flight_data_old.link_atad_time,
                            ams_flight_data_old.`4zucs_ad03_name`,
                            ams_flight_data_old.`4zucs_ad03_unique_flight_id`,
                            ams_flight_data_old.`linkedAirline`,
                            ams_flight_data_old.`linkedNumber`,
                            ams_flight_data_old.`BOOKED_PAX`,
                            ams_flight_data_old.`ADULT_PAX`,
                            ams_flight_data_old.v_landtakeoffdate,
                            ams_flight_data_old.v_landtakeofftime,
                            ams_flight_data_old.v_landtakeoffdate_ts,
                            ams_flight_data_old.v_landtakeoffdate_test,
                            ams_flight_data_old.v_landtakeofftime_test,
                            ams_flight_data_old.v_landtakeoffdate_test_ts,
                            ams_flight_data_old.v_atad_date,
                            ams_flight_data_old.v_atad_time,
                            ams_flight_data_old.v_atad_date_ts,
                            ams_flight_data_old.v_etad_date,
                            ams_flight_data_old.v_etad_time,
                            ams_flight_data_old.v_etad_date_ts,
                            ams_flight_data_old.v_chock_timedate,
                            ams_flight_data_old.v_chock_time,
                            ams_flight_data_old.v_chock_date,
                            ams_flight_data_old.reporting_date,
                            ams_flight_data_old.`GroundServices`,
                            ams_flight_data_old.window_start_unix,
                            ams_flight_data_old.window_end_unix,
                            ams_flight_data_old.ts,
                            ams_flight_data_old.v_body_type,
                            ams_flight_data_old.`4zucs_ad03_flight_number`,
                            ams_flight_data_old.`linkedFlightNumber`,
                            ams_flight_data_old.v_sto_ts,
                            ams_flight_data_old.v_sto_time,
                            ams_flight_data_old.v_tot_gecikme_dk,
                            ams_flight_data_old.v_tot_gecikme,
                            ams_flight_data_old.v_otp,
                            ams_flight_data_old.abs_taxitime,
                            ams_flight_data_old.v_tot_gecikme_dk_test,
                            ams_flight_data_old.v_tot_gecikme_test,
                            ams_flight_data_old.v_otp_test,
                            ams_flight_data_old.abs_taxitime_test,
                            ams_flight_data_old.p_pax,
                            ams_flight_data_old.v_gate,
                            ams_flight_data_old.`actualOffBlock`,
                            ams_flight_data_old.`targetOffBlock`,
                            ams_flight_data_old.takeoff,
                            ams_flight_data_old.`SUFFIX`,
                            ams_flight_data_old.v_type_max_pax,
                            ams_flight_data_old.deicing_start_date,
                            ams_flight_data_old.deicing_start_time,
                            ams_flight_data_old.deicing_end_date,
                            ams_flight_data_old.deicing_end_time,
                            ams_flight_data_old.id,
                            ams_flight_data_old.unique_flight_id,
                            ams_flight_data_old.suffix,
                            ams_flight_data_old.`timestamp`,
                            ams_flight_data_old.airline_iata,
                            ams_flight_data_old.airline_name,
                            ams_flight_data_old.flight_number,
                            ams_flight_data_old.actual_flight_number,
                            ams_flight_data_old.origin_city,
                            ams_flight_data_old.destination_city,
                            ams_flight_data_old.destination_iata,
                            ams_flight_data_old.flight_nature,
                            ams_flight_data_old.international_status,
                            ams_flight_data_old.scheduled_takeoff_date,
                            ams_flight_data_old.scheduled_takeoff_time,
                            ams_flight_data_old.scheduled_takeoff_time_gmt3,
                            ams_flight_data_old.scheduled_takeoff_timestamp,
                            ams_flight_data_old.actual_off_block_time,
                            ams_flight_data_old.target_off_block_time,
                            ams_flight_data_old.in_block_time,
                            ams_flight_data_old.takeoff_time,
                            ams_flight_data_old.landing_time,
                            ams_flight_data_old.atad_date,
                            ams_flight_data_old.atad_time,
                            ams_flight_data_old.atad_date_timestamp,
                            ams_flight_data_old.etad_date,
                            ams_flight_data_old.etad_time,
                            ams_flight_data_old.etad_date_timestamp,
                            ams_flight_data_old.chock_time_date,
                            ams_flight_data_old.chock_time,
                            ams_flight_data_old.chock_date,
                            ams_flight_data_old.land_takeoff_date,
                            ams_flight_data_old.land_takeoff_time,
                            ams_flight_data_old.land_takeoff_date_timestamp,
                            ams_flight_data_old.land_takeoff_date_test,
                            ams_flight_data_old.land_takeoff_time_test,
                            ams_flight_data_old.land_takeoff_date_test_timestamp,
                            ams_flight_data_old.aircraft_registration,
                            ams_flight_data_old.max_passengers,
                            ams_flight_data_old.aircraft_type_max_pax,
                            ams_flight_data_old.body_type,
                            ams_flight_data_old.service_type,
                            ams_flight_data_old.gate,
                            ams_flight_data_old.bay,
                            ams_flight_data_old.operational_status,
                            ams_flight_data_old.ground_services,
                            ams_flight_data_old.total_delay,
                            ams_flight_data_old.total_delay_minutes,
                            ams_flight_data_old.total_delay_minutes_test,
                            ams_flight_data_old.on_time_performance,
                            ams_flight_data_old.on_time_performance_test,
                            ams_flight_data_old.absolute_taxi_time,
                            ams_flight_data_old.absolute_taxi_time_test,
                            ams_flight_data_old.booked_passengers,
                            ams_flight_data_old.adult_passengers,
                            ams_flight_data_old.planned_passengers,
                            ams_flight_data_old.linked_airline,
                            ams_flight_data_old.linked_flight_number,
                            ams_flight_data_old.linked_flight_number_full,
                            ams_flight_data_old.linked_atad_date,
                            ams_flight_data_old.linked_atad_time,
                            ams_flight_data_old.window_start_unix_timestamp,
                            ams_flight_data_old.window_end_unix_timestamp,
                            concat(btrim(ams_flight_data_old.`4zucs_ad03_airline_iata`),
                                CASE
                                    WHEN right(ams_flight_data_old.`4zucs_ad03_actual_flight_number`, 1) RLIKE '[0-9]' THEN CAST(ams_flight_data_old.`4zucs_ad03_actual_flight_number` AS INT)
                                    ELSE CAST(left(ams_flight_data_old.`4zucs_ad03_actual_flight_number`, length(ams_flight_data_old.`4zucs_ad03_actual_flight_number`) - 1) AS INT)
                                END) AS flight_number_final
                           FROM stg.ams_flight_data_old
                          WHERE ams_flight_data_old.`4zucs_ad03_flight_nature` = 'ARRIVAL') inb_sto ON v.inbound_flight_date = CAST(CAST(concat(inb_sto.v_sto_date, ' ', inb_sto.v_sto_time_gmt3) AS TIMESTAMP) AS DATE) AND v.inb_flight_number = inb_sto.flight_number_final AND v.inbound_departure_airport = inb_sto.origin_iata
                     LEFT JOIN ( SELECT ams_flight_data_old._id,
                            ams_flight_data_old.`4zucs_ad03_airline_iata`,
                            ams_flight_data_old.`4zucs_ad03_destination_iata`,
                            ams_flight_data_old.`4zucs_ad03_origin_city`,
                            ams_flight_data_old.origin_iata,
                            ams_flight_data_old.`4zucs_ad03_flight_nature`,
                            ams_flight_data_old.`4zucs_ad03_actual_flight_number`,
                            ams_flight_data_old.v_sto_time_gmt3,
                            ams_flight_data_old.v_sto_date,
                            ams_flight_data_old.city,
                            ams_flight_data_old.`InBlock`,
                            ams_flight_data_old.landing,
                            ams_flight_data_old.`4zucs_ad03_service_type`,
                            ams_flight_data_old.`4zucs_ad03_int_status`,
                            ams_flight_data_old.`4zucs_ad03_registration`,
                            ams_flight_data_old.p_max_pax,
                            ams_flight_data_old.v_max_pax,
                            ams_flight_data_old.v_bay,
                            ams_flight_data_old.identifier,
                            ams_flight_data_old.code,
                            ams_flight_data_old.op_status,
                            ams_flight_data_old.callsign,
                            ams_flight_data_old.link_atad_date,
                            ams_flight_data_old.link_atad_time,
                            ams_flight_data_old.`4zucs_ad03_name`,
                            ams_flight_data_old.`4zucs_ad03_unique_flight_id`,
                            ams_flight_data_old.`linkedAirline`,
                            ams_flight_data_old.`linkedNumber`,
                            ams_flight_data_old.`BOOKED_PAX`,
                            ams_flight_data_old.`ADULT_PAX`,
                            ams_flight_data_old.v_landtakeoffdate,
                            ams_flight_data_old.v_landtakeofftime,
                            ams_flight_data_old.v_landtakeoffdate_ts,
                            ams_flight_data_old.v_landtakeoffdate_test,
                            ams_flight_data_old.v_landtakeofftime_test,
                            ams_flight_data_old.v_landtakeoffdate_test_ts,
                            ams_flight_data_old.v_atad_date,
                            ams_flight_data_old.v_atad_time,
                            ams_flight_data_old.v_atad_date_ts,
                            ams_flight_data_old.v_etad_date,
                            ams_flight_data_old.v_etad_time,
                            ams_flight_data_old.v_etad_date_ts,
                            ams_flight_data_old.v_chock_timedate,
                            ams_flight_data_old.v_chock_time,
                            ams_flight_data_old.v_chock_date,
                            ams_flight_data_old.reporting_date,
                            ams_flight_data_old.`GroundServices`,
                            ams_flight_data_old.window_start_unix,
                            ams_flight_data_old.window_end_unix,
                            ams_flight_data_old.ts,
                            ams_flight_data_old.v_body_type,
                            ams_flight_data_old.`4zucs_ad03_flight_number`,
                            ams_flight_data_old.`linkedFlightNumber`,
                            ams_flight_data_old.v_sto_ts,
                            ams_flight_data_old.v_sto_time,
                            ams_flight_data_old.v_tot_gecikme_dk,
                            ams_flight_data_old.v_tot_gecikme,
                            ams_flight_data_old.v_otp,
                            ams_flight_data_old.abs_taxitime,
                            ams_flight_data_old.v_tot_gecikme_dk_test,
                            ams_flight_data_old.v_tot_gecikme_test,
                            ams_flight_data_old.v_otp_test,
                            ams_flight_data_old.abs_taxitime_test,
                            ams_flight_data_old.p_pax,
                            ams_flight_data_old.v_gate,
                            ams_flight_data_old.`actualOffBlock`,
                            ams_flight_data_old.`targetOffBlock`,
                            ams_flight_data_old.takeoff,
                            ams_flight_data_old.`SUFFIX`,
                            ams_flight_data_old.v_type_max_pax,
                            ams_flight_data_old.deicing_start_date,
                            ams_flight_data_old.deicing_start_time,
                            ams_flight_data_old.deicing_end_date,
                            ams_flight_data_old.deicing_end_time,
                            ams_flight_data_old.id,
                            ams_flight_data_old.unique_flight_id,
                            ams_flight_data_old.suffix,
                            ams_flight_data_old.`timestamp`,
                            ams_flight_data_old.airline_iata,
                            ams_flight_data_old.airline_name,
                            ams_flight_data_old.flight_number,
                            ams_flight_data_old.actual_flight_number,
                            ams_flight_data_old.origin_city,
                            ams_flight_data_old.destination_city,
                            ams_flight_data_old.destination_iata,
                            ams_flight_data_old.flight_nature,
                            ams_flight_data_old.international_status,
                            ams_flight_data_old.scheduled_takeoff_date,
                            ams_flight_data_old.scheduled_takeoff_time,
                            ams_flight_data_old.scheduled_takeoff_time_gmt3,
                            ams_flight_data_old.scheduled_takeoff_timestamp,
                            ams_flight_data_old.actual_off_block_time,
                            ams_flight_data_old.target_off_block_time,
                            ams_flight_data_old.in_block_time,
                            ams_flight_data_old.takeoff_time,
                            ams_flight_data_old.landing_time,
                            ams_flight_data_old.atad_date,
                            ams_flight_data_old.atad_time,
                            ams_flight_data_old.atad_date_timestamp,
                            ams_flight_data_old.etad_date,
                            ams_flight_data_old.etad_time,
                            ams_flight_data_old.etad_date_timestamp,
                            ams_flight_data_old.chock_time_date,
                            ams_flight_data_old.chock_time,
                            ams_flight_data_old.chock_date,
                            ams_flight_data_old.land_takeoff_date,
                            ams_flight_data_old.land_takeoff_time,
                            ams_flight_data_old.land_takeoff_date_timestamp,
                            ams_flight_data_old.land_takeoff_date_test,
                            ams_flight_data_old.land_takeoff_time_test,
                            ams_flight_data_old.land_takeoff_date_test_timestamp,
                            ams_flight_data_old.aircraft_registration,
                            ams_flight_data_old.max_passengers,
                            ams_flight_data_old.aircraft_type_max_pax,
                            ams_flight_data_old.body_type,
                            ams_flight_data_old.service_type,
                            ams_flight_data_old.gate,
                            ams_flight_data_old.bay,
                            ams_flight_data_old.operational_status,
                            ams_flight_data_old.ground_services,
                            ams_flight_data_old.total_delay,
                            ams_flight_data_old.total_delay_minutes,
                            ams_flight_data_old.total_delay_minutes_test,
                            ams_flight_data_old.on_time_performance,
                            ams_flight_data_old.on_time_performance_test,
                            ams_flight_data_old.absolute_taxi_time,
                            ams_flight_data_old.absolute_taxi_time_test,
                            ams_flight_data_old.booked_passengers,
                            ams_flight_data_old.adult_passengers,
                            ams_flight_data_old.planned_passengers,
                            ams_flight_data_old.linked_airline,
                            ams_flight_data_old.linked_flight_number,
                            ams_flight_data_old.linked_flight_number_full,
                            ams_flight_data_old.linked_atad_date,
                            ams_flight_data_old.linked_atad_time,
                            ams_flight_data_old.window_start_unix_timestamp,
                            ams_flight_data_old.window_end_unix_timestamp,
                            concat(btrim(ams_flight_data_old.`4zucs_ad03_airline_iata`),
                                CASE
                                    WHEN right(ams_flight_data_old.`4zucs_ad03_actual_flight_number`, 1) RLIKE '[0-9]' THEN CAST(ams_flight_data_old.`4zucs_ad03_actual_flight_number` AS INT)
                                    ELSE CAST(left(ams_flight_data_old.`4zucs_ad03_actual_flight_number`, length(ams_flight_data_old.`4zucs_ad03_actual_flight_number`) - 1) AS INT)
                                END) AS flight_number_final
                           FROM stg.ams_flight_data_old
                          WHERE ams_flight_data_old.`4zucs_ad03_flight_nature` = 'DEPARTURE') outb_sto ON v.outbound_flight_date = CAST(CAST(concat(outb_sto.v_sto_date, ' ', outb_sto.v_sto_time_gmt3) AS TIMESTAMP) AS DATE) AND v.oub_flight_number = outb_sto.flight_number_final AND v.outbound_departure_airport = outb_sto.`4zucs_ad03_destination_iata`
                     LEFT JOIN test.dim_airport_2 iad ON iad.`Iata Code` = v.inbound_departure_airport
                     LEFT JOIN test.dim_airport_2 oad ON oad.`Iata Code` = v.outbound_departure_airport
                  WHERE v.message_type = 'BSM' AND v.passive = 0) q1) q;
