SELECT PROJECTION_NAME,
    PARTITION_KEY,
    round(SUM(ROS_SIZE_BYTES)/1024^3,2) size_gb,
    SUM(ROS_ROW_COUNT) row_count
FROM PARTITIONS
WHERE PROJECTION_NAME LIKE '%ARCSIGHT_IBB_WIFI_P2_B0%'
GROUP BY PROJECTION_NAME,
    PARTITION_KEY
    order by 2 desc